import { v4 as uuid } from "uuid";

export const products = [
  {
    id: uuid(),
    name: "Men's Casual Shirt",
    img: "https://dummyimage.com/300x400/000/fff&text=Shirt+1",
    alt: "Men's Casual Shirt",
    brand: "Roadster",
    newPrice: 899,
    oldPrice: 1299,
    discount: 30,
    size: "L",
    isIdealfor: "M",
    rating: 4.2,
  },
  {
    id: uuid(),
    name: "Women's Kurti",
    img: "https://dummyimage.com/300x400/f09/fff&text=Kurti+1",
    alt: "Women's Kurti",
    brand: "Biba",
    newPrice: 1099,
    oldPrice: 1599,
    discount: 31,
    size: "M",
    isIdealfor: "F",
    rating: 4.4,
  },
  {
    id: uuid(),
    name: "Men's Slim Fit Jeans",
    img: "https://dummyimage.com/300x400/222/fff&text=Jeans+1",
    alt: "Men's Jeans",
    brand: "Levi's",
    newPrice: 1499,
    oldPrice: 1999,
    discount: 25,
    size: "32",
    isIdealfor: "M",
    rating: 4.3,
  },
  {
    id: uuid(),
    name: "Women's High Waist Jeans",
    img: "https://dummyimage.com/300x400/ccf/000&text=Jeans+2",
    alt: "Women's Jeans",
    brand: "Zara",
    newPrice: 1799,
    oldPrice: 2299,
    discount: 22,
    size: "28",
    isIdealfor: "F",
    rating: 4.6,
  },
  {
    id: uuid(),
    name: "Unisex Hoodie",
    img: "https://dummyimage.com/300x400/666/fff&text=Hoodie+1",
    alt: "Unisex Hoodie",
    brand: "H&M",
    newPrice: 1299,
    oldPrice: 1799,
    discount: 27,
    size: "XL",
    isIdealfor: "U",
    rating: 4.5,
  },
  {
    id: uuid(),
    name: "Men's Formal Shirt",
    img: "https://dummyimage.com/300x400/444/fff&text=Shirt+2",
    alt: "Men's Formal Shirt",
    brand: "Arrow",
    newPrice: 1199,
    oldPrice: 1599,
    discount: 25,
    size: "L",
    isIdealfor: "M",
    rating: 4.1,
  },
  {
    id: uuid(),
    name: "Women's Maxi Dress",
    img: "https://dummyimage.com/300x400/f9f/000&text=Dress+1",
    alt: "Women's Maxi Dress",
    brand: "Forever 21",
    newPrice: 1499,
    oldPrice: 2199,
    discount: 32,
    size: "M",
    isIdealfor: "F",
    rating: 4.7,
  },
  {
    id: uuid(),
    name: "Men's Track Pants",
    img: "https://dummyimage.com/300x400/111/fff&text=Track+1",
    alt: "Men's Track Pants",
    brand: "Nike",
    newPrice: 999,
    oldPrice: 1399,
    discount: 28,
    size: "L",
    isIdealfor: "M",
    rating: 4.3,
  },
  {
    id: uuid(),
    name: "Women's Activewear T-Shirt",
    img: "https://dummyimage.com/300x400/f66/fff&text=Tshirt+1",
    alt: "Women's T-Shirt",
    brand: "Puma",
    newPrice: 699,
    oldPrice: 999,
    discount: 30,
    size: "S",
    isIdealfor: "F",
    rating: 4.2,
  },
  {
    id: uuid(),
    name: "Unisex Printed Sweatshirt",
    img: "https://dummyimage.com/300x400/0af/000&text=Sweatshirt+1",
    alt: "Unisex Sweatshirt",
    brand: "Adidas",
    newPrice: 1499,
    oldPrice: 1999,
    discount: 25,
    size: "L",
    isIdealfor: "U",
    rating: 4.6,
  },
];
